#!/bin/bash

### BEGIN INIT INFO
# Provides:          hornetq
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: Hornetq
# Description:       Start the Hornetq message broker
### END INIT INFO

# Check for existence of needed config file and read it
CONFIG=/etc/hornetq

HORNETQ_HOME=/usr/lib/hornetq

PID_FILE=/var/run/hornetq.pid

USER=hornetq

CLASSPATH="$HORNETQ_HOME/schemas:$CONFIG"

JARS=/usr/share/hornetq/lib

if [ ! -e $CONFIG ]; then
    echo "$CONFIG does not exists";
    exit 6;
fi

if [ ! -r $CONFIG ]; then
    echo "$CONFIG is not readable";
    exit 6;
fi

for i in "ls $JARS/*.jar"; do
    CLASSPATH=$i:$CLASSPATH
done

JVM_ARGS= cat "$CONFIG/jvm.properties"

HORNETQ_ARGS= cat "$CONFIG/hornetq.properties"

BOOTSTRAP_CLASS="org.hornetq.integration.bootstrap.HornetQBootstrapServer"

CMD="java $JVM_ARGS $HORNETQ_ARGS -classpath $CLASSPATH $BOOTSTRAP_CLASS hornetq-beans.xml"
RETVAL="0"

start() {
    echo -n "Starting HornetQ "

    start-stop-daemon --start --background --pidfile $PID_FILE --make-pidfile --user $USER --name $USER -x $CMD > /dev/null
}

stop() {
    echo -n "Shutting down HornetQ "
    start-stop-daemon --stop --user $USER --pidfile $PID_FILE
}

case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    restart)
    stop
    start
    ;;
    status)
    status -p $PID_FILE HornetQ
    RETVAL=$?    
    ;;
    *)
    echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload|probe}"
    exit 1
    ;;
esac
exit $RETVAL
