#!/bin/bash

### BEGIN INIT INFO
# Provides:          hornetq
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: Hornetq
# Description:       Start the Hornetq message broker
### END INIT INFO

# Check for existence of needed config file and read it
NAME=hornetq

CONFIG=/etc/$NAME

HORNETQ_HOME=/usr/lib/$NAME

PID_FILE=/var/run/$NAME.pid

HORNETQ_USER=$NAME

HORNETQ_GROUP=$NAME

CLASSPATH="$HORNETQ_HOME/schemas:$CONFIG"

JARS=/usr/share/$NAME/lib

#PATH=/usr/bin:/bin:/usr/sbin

if [ ! -e $CONFIG ]; then
    echo "$CONFIG does not exists";
    exit 6;
fi

if [ ! -r $CONFIG ]; then
    echo "$CONFIG is not readable";
    exit 6;
fi

for i in "ls $JARS/*.jar"; do
    CLASSPATH=$i:$CLASSPATH
done

JVM_ARGS=`cat $CONFIG/jvm.properties`

HORNETQ_ARGS=`cat $CONFIG/hornetq.properties`

BOOTSTRAP_CLASS="org.hornetq.integration.bootstrap.HornetQBootstrapServer"

INIT_FILE="hornetq-beans.xml"

CMD="java -cp $CLASSPATH $JVM_ARGS $HORNETQ_ARGS $BOOTSTRAP_CLASS $INIT_FILE"


start() {

    echo -n "Starting HornetQ "
    echo $CMD

    start-stop-daemon --start -b -p $PID_FILE --make-pidfile -u $HORNETQ_USER -g $HORNETQ_GROUP -c $HORNETQ_USER \
                      -x /bin/bash -- -c "$CMD"
}

stop() {
    echo -n "Shutting down HornetQ "
    start-stop-daemon --stop --user $HORNETQ_USER --pidfile $PID_FILE
}

case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    restart)
    stop
    start
    ;;
    status)
    status -p $PID_FILE HornetQ
    RETVAL=$?    
    ;;
    *)
    echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload|probe}"
    exit 1
    ;;
esac
exit $RETVAL
